// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: internal/features/onboard/adapters/inbound/grpc/proto/onboard.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OnboardOrganisationService_OnboardOrganisation_FullMethodName = "/proto.OnboardOrganisationService/OnboardOrganisation"
)

// OnboardOrganisationServiceClient is the client API for OnboardOrganisationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OnboardOrganisationServiceClient interface {
	OnboardOrganisation(ctx context.Context, in *OnboardOrganisationRequest, opts ...grpc.CallOption) (*OnboardOrganisationResponse, error)
}

type onboardOrganisationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOnboardOrganisationServiceClient(cc grpc.ClientConnInterface) OnboardOrganisationServiceClient {
	return &onboardOrganisationServiceClient{cc}
}

func (c *onboardOrganisationServiceClient) OnboardOrganisation(ctx context.Context, in *OnboardOrganisationRequest, opts ...grpc.CallOption) (*OnboardOrganisationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnboardOrganisationResponse)
	err := c.cc.Invoke(ctx, OnboardOrganisationService_OnboardOrganisation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OnboardOrganisationServiceServer is the server API for OnboardOrganisationService service.
// All implementations must embed UnimplementedOnboardOrganisationServiceServer
// for forward compatibility.
type OnboardOrganisationServiceServer interface {
	OnboardOrganisation(context.Context, *OnboardOrganisationRequest) (*OnboardOrganisationResponse, error)
	mustEmbedUnimplementedOnboardOrganisationServiceServer()
}

// UnimplementedOnboardOrganisationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOnboardOrganisationServiceServer struct{}

func (UnimplementedOnboardOrganisationServiceServer) OnboardOrganisation(context.Context, *OnboardOrganisationRequest) (*OnboardOrganisationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnboardOrganisation not implemented")
}
func (UnimplementedOnboardOrganisationServiceServer) mustEmbedUnimplementedOnboardOrganisationServiceServer() {
}
func (UnimplementedOnboardOrganisationServiceServer) testEmbeddedByValue() {}

// UnsafeOnboardOrganisationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OnboardOrganisationServiceServer will
// result in compilation errors.
type UnsafeOnboardOrganisationServiceServer interface {
	mustEmbedUnimplementedOnboardOrganisationServiceServer()
}

func RegisterOnboardOrganisationServiceServer(s grpc.ServiceRegistrar, srv OnboardOrganisationServiceServer) {
	// If the following call pancis, it indicates UnimplementedOnboardOrganisationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OnboardOrganisationService_ServiceDesc, srv)
}

func _OnboardOrganisationService_OnboardOrganisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnboardOrganisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OnboardOrganisationServiceServer).OnboardOrganisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OnboardOrganisationService_OnboardOrganisation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OnboardOrganisationServiceServer).OnboardOrganisation(ctx, req.(*OnboardOrganisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OnboardOrganisationService_ServiceDesc is the grpc.ServiceDesc for OnboardOrganisationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OnboardOrganisationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OnboardOrganisationService",
	HandlerType: (*OnboardOrganisationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnboardOrganisation",
			Handler:    _OnboardOrganisationService_OnboardOrganisation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/features/onboard/adapters/inbound/grpc/proto/onboard.proto",
}
