// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/features/onboard/adapters/grpc/proto/onboard.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnboardOrganisationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalName     *string                `protobuf:"bytes,1,opt,name=legalName,proto3,oneof" json:"legalName,omitempty"`
	TradingName   *string                `protobuf:"bytes,2,opt,name=tradingName,proto3,oneof" json:"tradingName,omitempty"`
	Website       *string                `protobuf:"bytes,3,opt,name=website,proto3,oneof" json:"website,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardOrganisationRequest) Reset() {
	*x = OnboardOrganisationRequest{}
	mi := &file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardOrganisationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardOrganisationRequest) ProtoMessage() {}

func (x *OnboardOrganisationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardOrganisationRequest.ProtoReflect.Descriptor instead.
func (*OnboardOrganisationRequest) Descriptor() ([]byte, []int) {
	return file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescGZIP(), []int{0}
}

func (x *OnboardOrganisationRequest) GetLegalName() string {
	if x != nil && x.LegalName != nil {
		return *x.LegalName
	}
	return ""
}

func (x *OnboardOrganisationRequest) GetTradingName() string {
	if x != nil && x.TradingName != nil {
		return *x.TradingName
	}
	return ""
}

func (x *OnboardOrganisationRequest) GetWebsite() string {
	if x != nil && x.Website != nil {
		return *x.Website
	}
	return ""
}

type OnboardOrganisationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnboardOrganisationResponse) Reset() {
	*x = OnboardOrganisationResponse{}
	mi := &file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardOrganisationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardOrganisationResponse) ProtoMessage() {}

func (x *OnboardOrganisationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardOrganisationResponse.ProtoReflect.Descriptor instead.
func (*OnboardOrganisationResponse) Descriptor() ([]byte, []int) {
	return file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescGZIP(), []int{1}
}

func (x *OnboardOrganisationResponse) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

var File_internal_features_onboard_adapters_grpc_proto_onboard_proto protoreflect.FileDescriptor

const file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDesc = "" +
	"\n" +
	";internal/features/onboard/adapters/grpc/proto/onboard.proto\x12\x05proto\"\xaf\x01\n" +
	"\x1aOnboardOrganisationRequest\x12!\n" +
	"\tlegalName\x18\x01 \x01(\tH\x00R\tlegalName\x88\x01\x01\x12%\n" +
	"\vtradingName\x18\x02 \x01(\tH\x01R\vtradingName\x88\x01\x01\x12\x1d\n" +
	"\awebsite\x18\x03 \x01(\tH\x02R\awebsite\x88\x01\x01B\f\n" +
	"\n" +
	"_legalNameB\x0e\n" +
	"\f_tradingNameB\n" +
	"\n" +
	"\b_website\"9\n" +
	"\x1bOnboardOrganisationResponse\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id2z\n" +
	"\x1aOnboardOrganisationService\x12\\\n" +
	"\x13OnboardOrganisation\x12!.proto.OnboardOrganisationRequest\x1a\".proto.OnboardOrganisationResponseBDZBorganisation/internal/features/onboard/adapters/inbound/grpc/protob\x06proto3"

var (
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescOnce sync.Once
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescData []byte
)

func file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescGZIP() []byte {
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescOnce.Do(func() {
		file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDesc), len(file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDesc)))
	})
	return file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDescData
}

var file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_features_onboard_adapters_grpc_proto_onboard_proto_goTypes = []any{
	(*OnboardOrganisationRequest)(nil),  // 0: proto.OnboardOrganisationRequest
	(*OnboardOrganisationResponse)(nil), // 1: proto.OnboardOrganisationResponse
}
var file_internal_features_onboard_adapters_grpc_proto_onboard_proto_depIdxs = []int32{
	0, // 0: proto.OnboardOrganisationService.OnboardOrganisation:input_type -> proto.OnboardOrganisationRequest
	1, // 1: proto.OnboardOrganisationService.OnboardOrganisation:output_type -> proto.OnboardOrganisationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_features_onboard_adapters_grpc_proto_onboard_proto_init() }
func file_internal_features_onboard_adapters_grpc_proto_onboard_proto_init() {
	if File_internal_features_onboard_adapters_grpc_proto_onboard_proto != nil {
		return
	}
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[0].OneofWrappers = []any{}
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDesc), len(file_internal_features_onboard_adapters_grpc_proto_onboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_features_onboard_adapters_grpc_proto_onboard_proto_goTypes,
		DependencyIndexes: file_internal_features_onboard_adapters_grpc_proto_onboard_proto_depIdxs,
		MessageInfos:      file_internal_features_onboard_adapters_grpc_proto_onboard_proto_msgTypes,
	}.Build()
	File_internal_features_onboard_adapters_grpc_proto_onboard_proto = out.File
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_goTypes = nil
	file_internal_features_onboard_adapters_grpc_proto_onboard_proto_depIdxs = nil
}
