// Code generated by MockGen. DO NOT EDIT.
// Source: internal/features/onboard/core/data/access/organisation_dao.go
//
// Generated by this command:
//
//	mockgen -source=internal/features/onboard/core/data/access/organisation_dao.go -destination=internal/features/onboard/core/data/access/organisation_dao_mock.go -package=access
//

// Package access is a generated GoMock package.
package access

import (
	"context"

	reflect "reflect"

	entities "github.com/ekko-earth/organisation/internal/features/onboard/core/data/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganisationDAO is a mock of OrganisationDAO interface.
type MockOrganisationDAO struct {
	ctrl     *gomock.Controller
	recorder *MockOrganisationDAOMockRecorder
	isgomock struct{}
}

// MockOrganisationDAOMockRecorder is the mock recorder for MockOrganisationDAO.
type MockOrganisationDAOMockRecorder struct {
	mock *MockOrganisationDAO
}

// NewMockOrganisationDAO creates a new mock instance.
func NewMockOrganisationDAO(ctrl *gomock.Controller) *MockOrganisationDAO {
	mock := &MockOrganisationDAO{ctrl: ctrl}
	mock.recorder = &MockOrganisationDAOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganisationDAO) EXPECT() *MockOrganisationDAOMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockOrganisationDAO) Count(organisation *entities.Organisation, context context.Context	) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", organisation)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockOrganisationDAOMockRecorder) Count(organisation any, context context.Context) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockOrganisationDAO)(nil).Count), organisation)
}

// Create mocks base method.
func (m *MockOrganisationDAO) Create(organisation *entities.Organisation, context context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", organisation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganisationDAOMockRecorder) Create(organisation any, context context.Context) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganisationDAO)(nil).Create), organisation)
}
